.. c404-future-docs documentation master file, created by
   sphinx-quickstart on Thu Jan  8 13:40:24 2026.
   You can adapt this file completely to your liking, but it should at least
   contain the root `toctree` directive.

=========================================================
Future Climate Simulation Documentation
=========================================================

    This living documentation contains the technical details for creating the CONUS404 dataset, the CONUS404 PGW dataset, and the PMP dataset, as well as the postprocessing details of the datasets.

    The presentations and publications resulted from this work will be added as they become available.

.. toctree::
   :hidden:
   
   introduction
   CONUS404-dataset
   CONUS404-PGW-dataset
   PMP-simulations
   postprocessing
   presentation-pubs
   references
   appendices
