.. vim: syntax=rst
.. include:: meta.rest

1. Introduction
===============
**Project Title: Future Climate Simulation Technical Support and Scientific Collaboration**

For a long time, high-hazard structures in the United States, including dams and nuclear power plants, have been engineered to withstand floods resulting from relatively rare but still likely extreme precipitation events, termed Probable Maximum Precipitation (PMP). More than 16,000 high-hazard dams and 50 nuclear power plants are located in the United States, many of which are approaching or exceeding their design lifetime. Failure of any one of these structures will likely result in loss of life and could impose significant economic losses and widespread environmental damage. The pressures of future climate fluctuations on flood hazards further highlight the urgent need to re-assess the safety of and flood protection provided by structures designed decades ago.

The scientific and engineering foundations of PMP were initially developed many decades ago to address the catastrophic impacts of the Great Flood of 1913 in the Upper Ohio River. Since then, the rapidly accelerating pace of dam building in the United States led to the standardization of PMP procedures by federal agencies in the 1940s. PMP informed rational engineering solutions for the U.S. water and power infrastructure to diminish risks of flood hazards. However, weaknesses in the scientific foundations of PMP, combined with advances in understanding, observing, and modeling extreme storms, call for fundamental changes to the definition of PMP and the methods used to estimate it. 

Based on this backbone, the National Academies of Science, Engineering, and Medicine recommends in its report, “Modernizing Probable Maximum Precipitation (PMP) Estimation” (June 2024), that NOAA should modernize extreme precipitation guidance for the nation’s critical infrastructure. The National Academies report recommends that NOAA should adopt a model-based approach to PMP estimation that aligns with the revised PMP definition, consisting of multi-model large ensemble kilometer-scale or finer-resolution modeling to construct the probability distribution of precipitation for PMP estimation.

In this project, NOAA PSL (Physical Sciences Laboratory) will collaborate with NCAR’s Research Applications Laboratory (RAL) to expand upon NCAR’s CONUS404 (CONUS domain hydroclimate simulations for a ~40 period at 4-km horizontal resolution) dataset to produce a portfolio of high-resolution model simulations taking place in probabilistically representative scenarios to respond to the National Academies recommendation of km-scale or finer continuous simulations.

.. image:: /_static/PMP_overview.png
   :alt: Overview of modernizing PMP estimation
   :align: center
   :width: 100%
