.. vim: syntax=rst
.. include:: meta.rest

4. Lossy compression
==================
The primary motivation for applying lossy compression is to reduce storage requirements while maintaining the data quality to the maximum extent possible, with a goal of achieving at least one order of magnitude reduction in file size.

Percentage change plots show the changes before and after applying lossy compression for CAPE and SIN variables.

Analyze CAPE and SIN fields using the Spur compression method and evaluate the impacts

Conduct benchmarking tests to measure changes in computation time required for various compression levels

.
