.. vim: syntax=rst
.. include:: meta.rest

6. Presentation and publication
===============================
**Project Title: Future Climate Simulation Technical Support and Scientific Collaboration**

Presentations and publications will be posted here when they become available.
